/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsms;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANK
 */
public class Bike_Details extends javax.swing.JFrame {
String modelid,model_name,supid;
 Integer sell_price,unitprice,quantity;
Date sup_date;
    /**
     * Creates new form Bike_Details
     */
    public Bike_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dtpbd = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        txtmn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnenter = new javax.swing.JButton();
        btnmoredetails = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        txtsp = new javax.swing.JTextField();
        txtsid = new javax.swing.JTextField();
        txtup = new javax.swing.JTextField();
        txtq = new javax.swing.JTextField();
        txtmid = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbd = new javax.swing.JTable();
        btnclear = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bike Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 260, 72));

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Model ID            :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 124, 240, 30));

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Model Name      :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 204, 250, 31));

        jLabel4.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sell Price           :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 230, 29));

        jLabel5.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Supplier ID        :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 363, 240, 31));

        jLabel6.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Supplying Date  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 442, 230, 33));

        jLabel7.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Unit Price          :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 240, 30));

        dtpbd.setBackground(new java.awt.Color(255, 255, 255));
        dtpbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtpbdActionPerformed(evt);
            }
        });
        jPanel1.add(dtpbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 440, 350, 40));

        jLabel8.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Quantity             :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 599, 240, 29));

        txtmn.setBackground(new java.awt.Color(255, 255, 255));
        txtmn.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtmn.setForeground(new java.awt.Color(0, 0, 0));
        txtmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmnActionPerformed(evt);
            }
        });
        jPanel1.add(txtmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 350, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 72, 700, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 960, 20));

        btnenter.setBackground(new java.awt.Color(0, 102, 204));
        btnenter.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnenter.setForeground(new java.awt.Color(255, 255, 255));
        btnenter.setText("ENTER");
        btnenter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnenter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });
        jPanel1.add(btnenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 120, 50));

        btnmoredetails.setBackground(new java.awt.Color(0, 102, 204));
        btnmoredetails.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnmoredetails.setForeground(new java.awt.Color(255, 255, 255));
        btnmoredetails.setText("MORE DETAILS");
        btnmoredetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmoredetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmoredetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoredetailsActionPerformed(evt);
            }
        });
        jPanel1.add(btnmoredetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 750, 180, 50));

        btnupdate.setBackground(new java.awt.Color(0, 102, 204));
        btnupdate.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 120, 50));

        txtsp.setBackground(new java.awt.Color(255, 255, 255));
        txtsp.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtsp.setForeground(new java.awt.Color(0, 0, 0));
        txtsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspActionPerformed(evt);
            }
        });
        jPanel1.add(txtsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 350, 40));

        txtsid.setBackground(new java.awt.Color(255, 255, 255));
        txtsid.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtsid.setForeground(new java.awt.Color(0, 0, 0));
        txtsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsidActionPerformed(evt);
            }
        });
        jPanel1.add(txtsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 350, 40));

        txtup.setBackground(new java.awt.Color(255, 255, 255));
        txtup.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtup.setForeground(new java.awt.Color(0, 0, 0));
        txtup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtupActionPerformed(evt);
            }
        });
        jPanel1.add(txtup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 350, 40));

        txtq.setBackground(new java.awt.Color(255, 255, 255));
        txtq.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtq.setForeground(new java.awt.Color(0, 0, 0));
        txtq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqActionPerformed(evt);
            }
        });
        jPanel1.add(txtq, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 350, 40));

        txtmid.setBackground(new java.awt.Color(255, 255, 255));
        txtmid.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtmid.setForeground(new java.awt.Color(0, 0, 0));
        txtmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmidActionPerformed(evt);
            }
        });
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 125, 350, 40));

        btnsearch.setBackground(new java.awt.Color(0, 102, 255));
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsms/vippng.com-search-png-images-1037268.png"))); // NOI18N
        btnsearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 60, 60));

        btnhome.setBackground(new java.awt.Color(0, 102, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsms/1 home-start-blue-logo-icon-0.png"))); // NOI18N
        btnhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 630, 60, 60));

        tblbd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblbd);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 660, 430));

        btnclear.setBackground(new java.awt.Color(0, 102, 204));
        btnclear.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR");
        btnclear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 120, 50));

        btndelete.setBackground(new java.awt.Color(0, 102, 204));
        btndelete.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE");
        btndelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1228, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dtpbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtpbdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtpbdActionPerformed

    private void txtmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnActionPerformed

    private void txtspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspActionPerformed

    private void txtsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidActionPerformed

    private void txtupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtupActionPerformed

    private void txtqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqActionPerformed

    private void txtmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmidActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
       Main mp=new Main();
          mp.setVisible(true);
          this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnmoredetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoredetailsActionPerformed
Bike_Description bmd=new Bike_Description();
bmd.setVisible(true);

this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnmoredetailsActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
DBConnection.Connect();
try
{
Statement st = DBConnection.con.createStatement();
ResultSet res = st.executeQuery("SELECT*FROM BIKE WHERE MODELID='"+this.txtmid.getText()+"'");
while(res.next())
{
this.txtmn.setText(res.getString("MODEL_NAME"));
this.txtsp.setColumns(res.getInt("SELL_PRICE"));
this.txtsid.setText(res.getString("SUPID"));
this.dtpbd.setDate(res.getDate("SUP_DATE"));
this.txtup.setColumns(res.getInt("UNITPRICE"));
        
this.txtq.setColumns(res.getInt("QUANTITY"));
        }
DBConnection.con.close();

}
catch(SQLException ex)
        {
        JOptionPane.showMessageDialog(null,ex.getMessage());
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
DBConnection.Connect();
       try
       {
           if(this.txtmid.getText().equals(""))
           {
           JOptionPane.showMessageDialog(this, "Model ID is required!");
           }
           else if(this.txtsid.getText().equals(""))
           {
           JOptionPane.showMessageDialog(this, "Supplier ID is required!");
           }
       
           else
       {
       Statement st=DBConnection.con.createStatement();
         st.executeUpdate("DELETE FROM BIKE WHERE MODELID='"+this.txtmid.getText()+"'");
         JOptionPane.showMessageDialog(this, "Record is deleted succesfully");
         DBConnection.con.close();
         LoadTable();
       }
       }
       catch(SQLException ex)
               {
               JOptionPane.showMessageDialog(this, ex.getMessage());
               }         // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
          this.txtmid.setText("");
          this.txtmn.setText("");
          this.txtq.setText("");
          this.txtsid.setText("");
          this.txtsp.setText(""); 
          this.txtup.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
       DBConnection.Connect();
        try
         
       {
           if(this.txtmid.getText().equals(""))
           {
           JOptionPane.showMessageDialog(this, "Model ID is required!");
           }
           else if(this.txtsid.getText().equals(""))
           {
           JOptionPane.showMessageDialog(this, "Supplier ID is required!");
           }
           else
       {
       Statement st=DBConnection.con.createStatement();
         st.executeUpdate("UPDATE BIKE SET MODEL_NAME='"+model_name+"',SELL_PRICE='"+sell_price+"',SUP_DATE='"+sup_date+"',UNITPRICE='"+unitprice+"',QUANTITY+'"+quantity+"'WHERE MODELID='"+this.txtmid.getText()+"'");
         JOptionPane.showMessageDialog(this, "Record is updated succesfully");
         DBConnection.con.close();
         LoadTable();
       }
       }
       catch(SQLException ex)
               {
               JOptionPane.showMessageDialog(this, ex.getMessage());
               }  // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenterActionPerformed
        LoadElements();
       DBConnection.Connect();
       try
       {
           if(this.txtmid.getText().equals(""))
           {
           JOptionPane.showMessageDialog(this, "Model ID is required!");
           }
           else if(this.txtsid.getText().equals(""))
           {
           JOptionPane.showMessageDialog(this, "Supplier ID is required");
           }
           else
       {
       Statement st=DBConnection.con.createStatement();
         st.executeUpdate("INSERT INTO BIKE VALUES('"+modelid+"','"+model_name+"','"+sell_price+"','"+supid+"','"+sup_date+"','"+unitprice+"','"+quantity+"')");
         JOptionPane.showMessageDialog(this, "Record is inserted succesfully");
         DBConnection.con.close();
         LoadTable();
       }
       }
       catch(SQLException ex)
               {
               JOptionPane.showMessageDialog(this, ex.getMessage());
               }
    }                                        

    private void txtsaActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

                    void LoadElements()
    {
    modelid=this.txtmid.getText();
    model_name=this.txtmn.getText();
   sell_price=this.txtsp.getColumns();
    supid=this.txtsid.getText();
    sup_date=this.dtpbd.getDate();
    unitprice=this.txtup.getColumns();
    quantity=this.txtq.getColumns();
    
    }
    void LoadTable()
    {
    DefaultTableModel dtm=new DefaultTableModel();
    dtm.addColumn("Model ID");
    dtm.addColumn("Model Name");
    dtm.addColumn("Sell Price");
    dtm.addColumn("Supplier ID");
    dtm.addColumn("Supplying Date");
    
    dtm.addColumn("Unit Price");
    dtm.addColumn("Quantity");
    
    
    DBConnection.Connect();
    try
    {
    Statement st=DBConnection.con.createStatement();
    ResultSet rs=st.executeQuery("SELECT * FROM BIKE");
    while(rs.next())
    {
    String MODELID = rs.getString("MODELID");
    String MODEL_NAME = rs.getString("MODEL_NAME");
    Integer SELL_PRICE = rs.getInt("SELL_PRICE");
         
    String SUPID= rs.getString("SUPID");
   Date SUPDATE = rs.getDate("SUPDATE");
    Integer UNITPRICE=rs.getInt("UNITPRICE");
    Integer QUANTITY=rs.getInt("QUANTITY");   
    dtm.addRow(new String[]{MODELID,MODEL_NAME,SUPID});
    dtm.addRow(new Date[]{SUPDATE});
    dtm.addRow(new Integer[]{UNITPRICE,QUANTITY,SELL_PRICE});
    }
    this.tblbd.setModel(dtm);
    DBConnection.con.close();
    }
    catch(SQLException ex)
            {
            JOptionPane.showMessageDialog(null,ex.getMessage());
            }                         

        
        //TODO add your handling code here
    }//GEN-LAST:event_btnenterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bike_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bike_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bike_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bike_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bike_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnmoredetails;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private org.jdesktop.swingx.JXDatePicker dtpbd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblbd;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtmn;
    private javax.swing.JTextField txtq;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txtsp;
    private javax.swing.JTextField txtup;
    // End of variables declaration//GEN-END:variables
 }

   

   

