/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsms;

/**
 *
 * @author ANK
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        btnBD = new javax.swing.JButton();
        btnCD = new javax.swing.JButton();
        btnSD = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBD.setBackground(new java.awt.Color(0, 153, 255));
        btnBD.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        btnBD.setForeground(new java.awt.Color(0, 0, 0));
        btnBD.setText("Bike Details");
        btnBD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDActionPerformed(evt);
            }
        });
        jPanel1.add(btnBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 240, 50));

        btnCD.setBackground(new java.awt.Color(0, 153, 255));
        btnCD.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        btnCD.setForeground(new java.awt.Color(0, 0, 0));
        btnCD.setText("Customer details");
        btnCD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDActionPerformed(evt);
            }
        });
        jPanel1.add(btnCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 250, 50));

        btnSD.setBackground(new java.awt.Color(0, 153, 255));
        btnSD.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        btnSD.setForeground(new java.awt.Color(0, 0, 0));
        btnSD.setText("Supplier Details");
        btnSD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSDActionPerformed(evt);
            }
        });
        jPanel1.add(btnSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 250, 50));

        btnP.setBackground(new java.awt.Color(0, 153, 255));
        btnP.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        btnP.setForeground(new java.awt.Color(0, 0, 0));
        btnP.setText("Purchase");
        btnP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });
        jPanel1.add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsms/bike-pc-blue 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 200, 200));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("WELCOME TO BIKE SALES MANAGEMENT SYSTEMS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 830, 80));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 70, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsms/computerworld_procurement_icon.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 200, 200));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsms/Pollock-Icons2-SupplierRelationship.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, 210, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsms/A iconfinder_User 2_86708.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 200, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1060, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDActionPerformed
       Customer_Details cd=new Customer_Details();
       cd.setVisible(true);
       cd.LoadTable();
       this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btnCDActionPerformed

    private void btnBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDActionPerformed
    Bike_Details bd=new Bike_Details();
    bd.setVisible(true);
    bd.setVisible(true);
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_btnBDActionPerformed

    private void btnSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSDActionPerformed
       Supplier_Details sd= new Supplier_Details();
       sd.setVisible(true);
       sd.LoadTable();
       this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnSDActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
 Purchase p=new Purchase();
       p.setVisible(true);
       
       p.LoadTable();
       this.setVisible(false);
              
// TODO add your handling code here:
    }//GEN-LAST:event_btnPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBD;
    private javax.swing.JButton btnCD;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnSD;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables

    void LoadTable() {
         //To change body of generated methods, choose Tools | Templates.
    }

    private static class p {

        public p() {
        }
    }
}
