/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANK
 */
public class Purchase extends javax.swing.JFrame {
String modelid,customerid,empname;
 Date buying_date;
    /**
     * Creates new form Purchase
     */
    public Purchase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        txten = new javax.swing.JTextField();
        txtmid = new javax.swing.JTextField();
        dtpp = new org.jdesktop.swingx.JXDatePicker();
        btnenter = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Purchase");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 220, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 890, 30));

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Employee Name     :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Buying Date           :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Model ID                :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Customer ID          :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtcid.setBackground(new java.awt.Color(255, 255, 255));
        txtcid.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtcid.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 260, 50));

        txten.setBackground(new java.awt.Color(255, 255, 255));
        txten.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txten.setForeground(new java.awt.Color(0, 0, 0));
        txten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenActionPerformed(evt);
            }
        });
        jPanel1.add(txten, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 260, 50));

        txtmid.setBackground(new java.awt.Color(255, 255, 255));
        txtmid.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtmid.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 260, 50));

        dtpp.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dtpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 260, 50));

        btnenter.setBackground(new java.awt.Color(0, 102, 204));
        btnenter.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnenter.setForeground(new java.awt.Color(255, 255, 255));
        btnenter.setText("ENTER");
        btnenter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnenter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });
        jPanel1.add(btnenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 140, 50));

        btnupdate.setBackground(new java.awt.Color(0, 102, 204));
        btnupdate.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 140, 50));

        btnclear.setBackground(new java.awt.Color(0, 102, 204));
        btnclear.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR");
        btnclear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 140, 50));

        btndelete.setBackground(new java.awt.Color(0, 102, 204));
        btndelete.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE");
        btndelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 140, 50));

        btnhome.setBackground(new java.awt.Color(0, 102, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsms/1 home-start-blue-logo-icon-0.png"))); // NOI18N
        btnhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 60, 60));

        btnsearch.setBackground(new java.awt.Color(0, 102, 255));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsms/vippng.com-search-png-images-1037268.png"))); // NOI18N
        btnsearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 60, 60));

        tblp.setBackground(new java.awt.Color(255, 255, 255));
        tblp.setForeground(new java.awt.Color(0, 0, 0));
        tblp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 490, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenActionPerformed

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenterActionPerformed
        LoadElements();
        DBConnection.Connect();
        try
        {
            if(this.txtmid.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Model ID is required!");
            }
           
             else if(this.txtcid.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Customer ID is required!");
            }
              else if(this.txten.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Employee Name is required!");
            }
               else if(this.dtpp.getDate() == null)
            {
                JOptionPane.showMessageDialog(this, "Buying Date is required!");
            }

            else
            {
                Statement st=DBConnection.con.createStatement();
                st.executeUpdate("INSERT INTO BUY VALUES('"+modelid+"','"+customerid+"','"+buying_date+"','"+empname+"')");
                JOptionPane.showMessageDialog(this, "Record is inserted succesfully");
                DBConnection.con.close();
                LoadTable();
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnenterActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        LoadElements();
        DBConnection.Connect();
        try

        {
            if(this.txtmid.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Model ID is required!");
            }
            else if(this.txtcid.getText().equals(""))
            {
            JOptionPane.showMessageDialog(this,"Customer ID is required!");
            }

            else
            {
                Statement st=DBConnection.con.createStatement();
                st.executeUpdate("UPDATE BUY SET BUYING_DATE='"+buying_date+"',EMPNAME='"+empname+"' WHERE MODELID='"+this.txtmid.getText()+"' AND CUSTOMERID='"+this.txtcid.getText()+"'");
                JOptionPane.showMessageDialog(this, "Record is updated succesfully");
                DBConnection.con.close();
                LoadTable();
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        this.txtmid.setText("");
        this.txtcid.setText("");
        this.txten.setText("");
        this.dtpp.setDate(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        DBConnection.Connect();
        try
        {
            if(this.txtmid.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Model ID is required!");
            }
            else if(this.txtcid.getText().equals(""))
            {
            JOptionPane.showMessageDialog(this, "Customer ID is required!");
            }

            else
            {
                Statement st=DBConnection.con.createStatement();
                st.executeUpdate("DELETE FROM BUY WHERE MODELID='"+this.txtmid.getText()+"'AND CUSTOMERID='"+this.txtcid.getText()+"'");
                JOptionPane.showMessageDialog(this, "Record is deleted succesfully");
                DBConnection.con.close();
                LoadTable();
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }  // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        Main mp=new Main();
        mp.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        DBConnection.Connect();
        try
        {
            Statement st = DBConnection.con.createStatement();
            ResultSet res = st.executeQuery("SELECT*FROM BUY WHERE MODELID='"+this.txtmid.getText()+"'");
            while(res.next())
            {
                this.txtcid.setText(res.getString("CUSTOMERID"));
                this.txtmid.setText(res.getString("MODELID"));
                this.txten.setText(res.getString("EMPNAME"));
                this.dtpp.setDate(res.getDate("BUYING_DATE"));
            }
            DBConnection.con.close();

        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());

        }// TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed
      void LoadElements()
      {
      modelid=this.txtmid.getText();
      customerid=this.txtcid.getText();
      buying_date=this.dtpp.getDate();
      empname=this.txten.getText();
      
      
      }
      void LoadTable()
      {
      DefaultTableModel dtm=new DefaultTableModel();
    dtm.addColumn("Model ID");
    dtm.addColumn("Customer ID");
    dtm.addColumn("Buying_Date");
    dtm.addColumn("Employee Name");
    
    
    
    DBConnection.Connect();
    try
    {
    Statement st=DBConnection.con.createStatement();
    ResultSet rs=st.executeQuery("SELECT * FROM BUY");
    while(rs.next())
    {
    String MODELID = rs.getString("MODELID");
    String CUSTOMERID = rs.getString("CUSTOMERID");
    String EMPNAME = rs.getString("EMPNAME");
         
    Date BUYING_DATE = rs.getDate("BUYING_DATE");
    
    dtm.addRow(new String[]{MODELID,CUSTOMERID,EMPNAME});
    dtm.addRow(new Date[]{BUYING_DATE  });
    }
    this.tblp.setModel(dtm);
    DBConnection.con.close();
    }
    catch(SQLException ex)
            {
            JOptionPane.showMessageDialog(null,ex.getMessage());
            }
      
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private org.jdesktop.swingx.JXDatePicker dtpp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblp;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txten;
    private javax.swing.JTextField txtmid;
    // End of variables declaration//GEN-END:variables
}
