/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANK
 */
public class Supplier_Details extends javax.swing.JFrame {

    String suppid,name,address,office,mobile;
    /**
     * Creates new form Supplier_Details
     */
    public Supplier_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        txtsn = new javax.swing.JTextField();
        txtsid = new javax.swing.JTextField();
        txtsa = new javax.swing.JTextField();
        txtsmono = new javax.swing.JTextField();
        txtshno = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        jSeparator2 = new javax.swing.JSeparator();
        btnenter = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsd = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(0, 153, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("DejaVu Serif", 1, 36)); // NOI18N
        label1.setText("Supplier Details");
        panel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        txtsn.setBackground(new java.awt.Color(255, 255, 255));
        txtsn.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtsn.setForeground(new java.awt.Color(0, 0, 0));
        txtsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsnActionPerformed(evt);
            }
        });
        panel1.add(txtsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 460, 40));

        txtsid.setBackground(new java.awt.Color(255, 255, 255));
        txtsid.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtsid.setForeground(new java.awt.Color(0, 0, 0));
        txtsid.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                txtsidComponentHidden(evt);
            }
        });
        txtsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsidActionPerformed(evt);
            }
        });
        panel1.add(txtsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 460, 40));

        txtsa.setBackground(new java.awt.Color(255, 255, 255));
        txtsa.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        txtsa.setForeground(new java.awt.Color(0, 0, 0));
        txtsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsaActionPerformed(evt);
            }
        });
        panel1.add(txtsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 383, 460, 40));

        txtsmono.setBackground(new java.awt.Color(255, 255, 255));
        txtsmono.setFont(new java.awt.Font("DejaVu Serif", 0, 18)); // NOI18N
        txtsmono.setForeground(new java.awt.Color(0, 0, 0));
        panel1.add(txtsmono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, 230, 40));

        txtshno.setBackground(new java.awt.Color(255, 255, 255));
        txtshno.setFont(new java.awt.Font("DejaVu Serif", 0, 18)); // NOI18N
        txtshno.setForeground(new java.awt.Color(0, 0, 0));
        panel1.add(txtshno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 230, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 890, 10));

        label9.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        label9.setText("Supplier ID        :");
        panel1.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 230, -1));

        label10.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        label10.setText("Phone No");
        panel1.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        label11.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        label11.setText("Home No    :");
        panel1.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, -1));

        label12.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        label12.setText("Address             :");
        panel1.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        label13.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        label13.setText("Mobile No  :");
        panel1.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, -1, -1));

        label14.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        label14.setText("Supplier Name  :");
        panel1.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 610, -1));

        btnenter.setBackground(new java.awt.Color(0, 102, 204));
        btnenter.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnenter.setForeground(new java.awt.Color(255, 255, 255));
        btnenter.setText("ENTER");
        btnenter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnenter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });
        panel1.add(btnenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 140, 50));

        btndelete.setBackground(new java.awt.Color(0, 102, 204));
        btndelete.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE");
        btndelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        panel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 820, 140, 50));

        btnupdate.setBackground(new java.awt.Color(0, 102, 204));
        btnupdate.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        panel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 140, 50));

        btnclear.setBackground(new java.awt.Color(0, 102, 204));
        btnclear.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR");
        btnclear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        panel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 730, 140, 50));

        btnhome.setBackground(new java.awt.Color(0, 102, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsms/1 home-start-blue-logo-icon-0.png"))); // NOI18N
        btnhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        panel1.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 900, 60, 60));

        btnsearch.setBackground(new java.awt.Color(0, 102, 255));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsms/vippng.com-search-png-images-1037268.png"))); // NOI18N
        btnsearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        panel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 900, 60, 60));

        tblsd.setAutoCreateRowSorter(true);
        tblsd.setBackground(new java.awt.Color(0, 153, 255));
        tblsd.setForeground(new java.awt.Color(0, 0, 0));
        tblsd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblsd.setGridColor(new java.awt.Color(0, 0, 0));
        tblsd.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblsd.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblsd);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 712, 570, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsidComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtsidComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidComponentHidden

    private void txtsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidActionPerformed

    private void txtsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsnActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
      DBConnection.Connect();
       try
       {
           if(this.txtsid.getText().equals(""))
           {
           JOptionPane.showMessageDialog(this, "Supplier ID is required!");
           }
       
           else
       {
       Statement st=DBConnection.con.createStatement();
         st.executeUpdate("DELETE FROM SUPPLIER WHERE SUPID='"+this.txtsid.getText()+"'");
         JOptionPane.showMessageDialog(this, "Record is deleted succesfully");
         DBConnection.con.close();
         LoadTable();
       }
       }
       catch(SQLException ex)
               {
               JOptionPane.showMessageDialog(this, ex.getMessage());
               }  // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
          this.txtsa.setText("");
          this.txtsid.setText("");
          this.txtshno.setText("");
          this.txtsmono.setText("");
          this.txtsn.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
 Main mp=new Main();
        mp.setVisible(true);
       this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenterActionPerformed
       LoadElements();
       DBConnection.Connect();
       try
       {
           if(this.txtsid.getText().equals(""))
           {
           JOptionPane.showMessageDialog(this, "Supplier ID is required!");
           }
       
           else
       {
       Statement st=DBConnection.con.createStatement();
         st.executeUpdate("INSERT INTO SUPPLIER VALUES('"+suppid+"','"+name+"','"+address+"','"+office+"','"+mobile+"')");
         JOptionPane.showMessageDialog(this, "Record is inserted succesfully");
         DBConnection.con.close();
         LoadTable();
       }
       }
       catch(SQLException ex)
               {
               JOptionPane.showMessageDialog(this, ex.getMessage());
               }
    }//GEN-LAST:event_btnenterActionPerformed

    private void txtsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsaActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
DBConnection.Connect();
try
{
Statement st = DBConnection.con.createStatement();
ResultSet res = st.executeQuery("SELECT*FROM SUPPLIER WHERE SUPID='"+this.txtsid.getText()+"'");
while(res.next())
{
this.txtsn.setText(res.getString("SUP_NAME"));
this.txtsa.setText(res.getString("ADDRESS"));
this.txtsmono.setText(res.getString("MOBILE"));
this.txtshno.setText(res.getString("OFFICE"));
        }
DBConnection.con.close();

}
catch(SQLException ex)
        {
        JOptionPane.showMessageDialog(null,ex.getMessage());
        
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
     DBConnection.Connect();
        try
         
       {
           if(this.txtsid.getText().equals(""))
           {
           JOptionPane.showMessageDialog(this, "Supplier ID is required!");
           }
       
           else
       {
       Statement st=DBConnection.con.createStatement();
         st.executeUpdate("UPDATE SUPPLIER SET SUP_NAME='"+name+"',ADDRESS='"+address+"',MOBILE='"+mobile+"',OFFICE='"+office+"' WHERE SUPID='"+this.txtsid.getText()+"'");
         JOptionPane.showMessageDialog(this, "Record is updated succesfully");
         DBConnection.con.close();
         LoadTable();
       }
       }
       catch(SQLException ex)
               {
               JOptionPane.showMessageDialog(this, ex.getMessage());
               } // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    void LoadElements()
    {
    suppid=this.txtsid.getText();
    name=this.txtsn.getText();
    address=this.txtsa.getText();
    office=this.txtshno.getText();
    mobile=this.txtsmono.getText();
    
    }
    void LoadTable()
    {
    DefaultTableModel dtm=new DefaultTableModel();
    dtm.addColumn("Supplier ID");
    dtm.addColumn("Name");
    dtm.addColumn("Address");
    dtm.addColumn("Office No");
    dtm.addColumn("Mobile No");
    
    
    DBConnection.Connect();
    try
    {
    Statement st=DBConnection.con.createStatement();
    ResultSet rs=st.executeQuery("SELECT * FROM SUPPLIER");
    while(rs.next())
    {
    String sid = rs.getString("SUPID");
    String NAME = rs.getString("SUP_NAME");
    String ADDRESS = rs.getString("ADDRESS");
         
    String MOBILE = rs.getString("MOBILE");
    String OFFICE = rs.getString("OFFICE");
    dtm.addRow(new String[]{sid,NAME,ADDRESS,MOBILE,OFFICE});
    }
    this.tblsd.setModel(dtm);
    DBConnection.con.close();
    }
    catch(SQLException ex)
            {
            JOptionPane.showMessageDialog(null,ex.getMessage());
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label9;
    private java.awt.Panel panel1;
    private javax.swing.JTable tblsd;
    private javax.swing.JTextField txtsa;
    private javax.swing.JTextField txtshno;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txtsmono;
    private javax.swing.JTextField txtsn;
    // End of variables declaration//GEN-END:variables
}
